export default {
    "login": "ursamresh",
    "id": 85226760,
    "node_id": "MDQ6VXNlcjg1MjI2NzYw",
    "avatar_url": "https://avatars.githubusercontent.com/u/85226760?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ursamresh",
    "html_url": "https://github.com/ursamresh",
    "followers_url": "https://api.github.com/users/ursamresh/followers",
    "following_url": "https://api.github.com/users/ursamresh/following{/other_user}",
    "gists_url": "https://api.github.com/users/ursamresh/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ursamresh/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ursamresh/subscriptions",
    "organizations_url": "https://api.github.com/users/ursamresh/orgs",
    "repos_url": "https://api.github.com/users/ursamresh/repos",
    "events_url": "https://api.github.com/users/ursamresh/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ursamresh/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Amresh Maurya",
    "company": "@ursamresh",
    "blog": "https://ursamresh.netlify.app/",
    "location": "Rohtak,Haryana,India",
    "email": null,
    "hireable": null,
    "bio": "Web Developer | JavaScript | NodeJS |  React JS | TailwindCSS | SASS  | C++ | C | Java | 2🌟@Codechef | 2🌟@Hackerrank |\r\n\r\n",
    "twitter_username": 'ursamresh',
    "public_repos": 21,
    "public_gists": 0,
    "followers": 1,
    "following": 3,
    "created_at": "2021-06-02T10:01:22Z",
    "updated_at": "2023-04-01T08:03:39Z"
    }